name: Deploy App to EC2

on:
  push:
    branches:
      - deployment # runs only when this branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # FRONTEND
      - run: |
          cd frontend
          npm ci
          npm run build

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend/build/*"
          target: "/var/www/chai.karansuthar.works"
          overwrite: true

      # ADMIN
      - run: |
          cd admin
          npm ci
          npm run build

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "admin/build/*"
          target: "/var/www/admin.chai.karansuthar.works"
          overwrite: true

      # BACKEND
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/*"
          target: "~/backend"
          overwrite: true

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/backend
            npm ci --production
            pm2 restart all || pm2 start server.js --name backend
            sudo systemctl restart nginx
